name: Tests

on:
  push:
    branches:
      - version-15
      - version-16
      - version-16
      - version-16
  pull_request:

concurrency:
  group: version-15-saml-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  contents: write
  checks: write
  issues: write
  pull-requests: write

jobs:
  tests:
    name: Server
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: YES
          MYSQL_ROOT_PASSWORD: 'admin'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Add to Hosts
        run: echo "127.0.0.1 test_site" | sudo tee -a /etc/hosts

      - name: Install Poetry
        uses: abatilo/actions-poetry@v4

      - name: Cache Poetry
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Install App Dependencies
        run: bash ${{ github.workspace }}/.github/helper/install_dependencies.sh

      - name: Install Bench Site and Apps
        env:
          MYSQL_HOST: 'localhost'
          MYSQL_PWD: 'admin'
        run: bash ${{ github.workspace }}/.github/helper/install.sh

      - name: Run Frappe Tests
        working-directory: /home/runner/frappe-bench
        run: |
          bench --site test_site set-config allow_tests true
          bench --site test_site run-tests --app saml

      - name: Run Pytest Tests
        working-directory: /home/runner/frappe-bench
        run: |
          source env/bin/activate
          cd apps/saml
          poetry install
          pytest --cov=saml --cov-report=xml --disable-warnings -s | tee pytest-coverage.txt
        env:
          TYPE: server

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: /home/runner/frappe-bench/apps/saml/pytest-coverage.txt
          pytest-xml-coverage-path: /home/runner/frappe-bench/apps/saml/coverage.xml
